# Generated by Django 5.0.6 on 2024-07-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubequery",
            name="latest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youtube_queries",
                to="notifier.youtubevideo",
            ),
        ),
    ]
