# Generated by Django 5.0.6 on 2024-07-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0003_email_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_sent",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
