# Generated by Django 5.0.6 on 2024-07-17 13:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0004_subscription_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("cf14b245-d1d1-47ea-b4bd-142af5c0fdb0"),
                editable=False,
                unique=True,
            ),
        ),
    ]
