# Generated by Django 5.0.6 on 2024-07-19 12:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0006_alter_subscription_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("ba592769-7c92-4839-b6a9-5d22d47a2f83"),
                editable=False,
                unique=True,
            ),
        ),
    ]
